function structToHeader(sections, headerFile)
% structToHeader(sections, headerFile)
%
% Bu fonksiyon, parseTxtToStruct() çıktısı olan "sections" struct dizisini
% kullanarak C dili uyumlu bir .h dosyası oluşturur.
%
% Her bölüm için:
%   - 32-bit adres
%   - veri uzunluğu
%   - 32-bit hex veriler
%
% headerFile: örn. 'firmware_data.h'

    fid = fopen(headerFile, 'w');
    if fid == -1
        error('Dosya oluşturulamadı: %s', headerFile);
    end

    fprintf(fid, '// Auto-generated firmware data header\n');
    fprintf(fid, '// Generated by structToHeader() on %s\n', datestr(now));
    fprintf(fid, '// 32 bit Veriler Little Endiandan Big endiana döndürüldü\n');
    fprintf(fid, '// Design by Akif\n\n\n');
    fprintf(fid, '#ifndef FIRMWARE_DATA_H\n#define FIRMWARE_DATA_H\n\n');
    fprintf(fid, '#include <stdint.h>\n\n');

    % Her bir section için C dizisi yaz
    for i = 1:numel(sections)
        addr = sections(i).address;
        len  = sections(i).length;
        data = sections(i).data;

        % Dizi adı (örnek: section_0001_data)
        varName = sprintf('section_%04d_data', i);

        % Dizi tanımı
        fprintf(fid, 'static const uint32_t %s[%d] = {\n', varName, len);

        % Verileri 8'li gruplar halinde yaz
        for j = 1:len
            if mod(j,8) == 1
                fprintf(fid, '    ');
            end
            fprintf(fid, '0x%08X', data(j));
            if j ~= len
                fprintf(fid, ', ');
            end
            if mod(j,8) == 0 || j == len
                fprintf(fid, '\n');
            end
        end
        fprintf(fid, '};\n\n');

        % Section bilgisi
        fprintf(fid, '// Address: 0x%08X, Length: %d words\n\n', addr, len);
    end

    % Ana diziyi tanımla
    fprintf(fid, 'typedef struct {\n');
    fprintf(fid, '    uint32_t address;\n');
    fprintf(fid, '    uint32_t length;\n');
    fprintf(fid, '    const uint32_t *data;\n');
    fprintf(fid, '} firmware_section_t;\n\n');

    fprintf(fid, 'static const firmware_section_t firmware_sections[%d] = {\n', numel(sections));
    for i = 1:numel(sections)
        fprintf(fid, '    { 0x%08X, %d, section_%04d_data }', ...
            sections(i).address, sections(i).length, i);
        if i ~= numel(sections)
            fprintf(fid, ',\n');
        else
            fprintf(fid, '\n');
        end
    end
    fprintf(fid, '};\n\n');

    fprintf(fid, '#endif // FIRMWARE_DATA_H\n');
    fclose(fid);

    fprintf('✅ Header dosyası oluşturuldu: %s\n', headerFile);
end